BootStrap: yum
OSVersion: 7
MirrorURL: https://www.mirrorservice.org/sites/mirror.centos.org/%{OSVERSION}/os/$basearch/
UpdateURL: https://www.mirrorservice.org/sites/mirror.centos.org/%{OSVERSION}/updates/$basearch/
Include: yum

%post
    yum update -y
    yum install -y git wget
    yum install -y centos-release-dotnet
    yum install -y rh-dotnetcore11

    cd /opt && wget https://github.com/Illumina/canvas/releases/download/1.31.0.843%2Bmaster/Canvas-1.31.0.843.master_x64.tar.gz
    cd /opt && tar zxvf Canvas-1.31.0.843.master_x64.tar.gz
    cd /opt && ln -s /opt/Canvas-1.31.0.843+master_x64 /opt/Canvas

    mkdir -p /apps /gpfs0 /gpfs1 /gpfs2 /well /users/

%runscript
    scl enable rh-dotnetcore11 "dotnet $@"

%labels
    Maintainer Adam Huffman
    Version v0.3
